# Generated by Django 3.1.7 on 2021-04-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210405_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='tumbnail',
            field=models.ImageField(upload_to='static/post/preview/'),
        ),
    ]
