# Generated by Django 3.1.7 on 2021-05-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210405_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='name',
            field=models.CharField(default='no name', max_length=60),
        ),
    ]
