# Generated by Django 3.1.7 on 2021-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_pic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='Description',
        ),
        migrations.AddField(
            model_name='pic',
            name='des_sizes',
            field=models.TextField(default=1, max_length=360),
            preserve_default=False,
        ),
    ]
