# Generated by Django 3.1.7 on 2021-05-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20210530_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='og_image',
            new_name='image_files',
        ),
    ]
